apiVersion: v1
kind: Service
metadata:
  name: <PROJECT>-web
#  namespace: <PROJECT>
  labels:
    app: <PROJECT>-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: <PROJECT>-web
